name: zeronet_ws
description: ZeroNet(X) WebSocket Package to use ZeroNet API via Websockets in your dart program.
version: 1.1.0
homepage: https://github.com/canewsin/zeronet_ws

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  plugin_platform_interface: ^2.0.2
  js: ^0.6.4
  html: ^0.15.1
  http: ^0.13.3
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - js/

  plugin:
    platforms:
      android:
        dartPluginClass: ZeroNetWSIO
      ios:
        dartPluginClass: ZeroNetWSIO
      windows:
        dartPluginClass: ZeroNetWSIO
      linux:
        dartPluginClass: ZeroNetWSIO
      macos:
        dartPluginClass: ZeroNetWSIO
      web:
        pluginClass: ZeroNetWSWeb
        fileName: zeronet_ws.dart